# Generated by Django 6.0.3 on 2026-05-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medication_keywords_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
