# Generated by Django 6.0.3 on 2026-05-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_order_created_at_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('description', models.TextField()),
                ('medication1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_med1', to='inventory.medication')),
                ('medication2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_med2', to='inventory.medication')),
            ],
        ),
    ]
